
- name: Install necessary dependencies
  hosts: webservers
  vars: 
    dns_and_reverse_proxies:
    - { domain: "34b446db-d550-4c6a-9e12-22f1f18bfd7e.pub.instances.scw.cloud", present: true, caddy_served: true, port: 8000, ssl: true }

  tasks:
  - name: Ensure Caddy is at the latest version
    ansible.builtin.dnf:
      name: caddy
      state: latest
  - name: Ensure uv is at the latest version
    ansible.builtin.dnf:
      name: uv
      state: latest
  - name: Enable and start Caddy
    ansible.builtin.systemd:
      name: caddy
      enabled: true
      state: started
  - name: Configure Caddy
    block:
    - name: Add proxy to Caddyfile
      ansible.builtin.copy:
        content: |
          {% if not item.ssl %}http://{% endif %}{{ item.domain }} {
            reverse_proxy :{{ item.port }}
          }          
        dest: /etc/caddy/Caddyfile.d/{{item.domain}}.caddyfile
      when: item.caddy_served
      loop: "{{ dns_and_reverse_proxies }}"
    when: item.present
  - name: Reload Caddy
    ansible.builtin.systemd:
      name: caddy
      state: reloaded
